name: CI (Supabase local verify)

on:
  pull_request:
    branches: [develop, main]
  # 额外增加 push 触发，解决 PR 合并性计算异常导致的检查“0/挂起”问题
  # 避免和生产部署重复，这里忽略 main；如需更严格也可加 develop
  push:
    branches-ignore:
      - main
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Supabase CLI
        uses: supabase/setup-cli@v1
        with:
          version: latest

      - name: Start local stack & apply migrations
        run: |
          echo "Starting Supabase local development environment..."
          supabase db start

          echo "Resetting database with migrations..."
          supabase db reset

          echo "Verifying migrations applied successfully..."
          # Generate diff; expect no drift after a clean reset
          supabase db diff --schema public > schema_diff.sql || true
          if [ -s schema_diff.sql ]; then
            echo "Schema drift detected after reset (should be empty):";
            cat schema_diff.sql;
            exit 1;
          else
            echo "No schema drift detected (OK).";
          fi

      - name: Stop local stack
        if: always()
        run: |
          echo "Stopping Supabase local development environment..."
          supabase db stop || true
